#! /usr/bin/env python3.10

import os, sys
from src import _debug, _warn, _help, _render, _xrender, _run

def main() -> None:
	"""Main"""
	if len(sys.argv) == 1 or '--help' in sys.argv:
		_help()

	if 'run' in sys.argv:
		_run(sys.argv[1])
	
	if 'render' in sys.argv:
		_render(sys.argv[1])

	if 'xrender' in sys.argv:
		_xrender(sys.argv[1], sys.argv[-1])

	if 'debug' in sys.argv:
		_debug(sys.argv[1])

	else:
		_help()


if __name__ == '__main__':
	main()
